# Generated by Django 3.1.5 on 2021-02-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210202_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
