# Generated by Django 3.1.5 on 2021-02-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='design',
            new_name='test',
        ),
    ]
