# Generated by Django 3.1.5 on 2021-02-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210203_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='content',
            new_name='durability',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='usability',
            new_name='price',
        ),
    ]
