# Generated by Django 3.1.5 on 2021-02-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210203_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='durability',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='price',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='test',
            new_name='usability',
        ),
    ]
