# Generated by Django 3.1.5 on 2021-02-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210203_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='content',
            new_name='durability',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='design',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='usability',
            new_name='test',
        ),
    ]
